core/urls.py
from django.urls import path
from core.views import *

app_name = "core"
urlpatterns = [
    path("", index, name = "index"),
    path("products/", product_list_view, name = "product-list"),
    path("product/<pid>/", product_detail_view, name = "product-detail"),
    path("category/", category_list_view, name = "category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    path("custom/", custom_product_list, name="custom"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax_add_review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("checkout/", checkout_view, name="checkout"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("payment-compeleted/", payment_compeleted_view, name="payment-compeleted"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-adress/", make_adress_default, name="make-default-adress"),
    path("contact/", contact_view, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


    path("checkout-information/", checkout_information_view, name="checkout-information"),




    




]

plannershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]   


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.register_view, name = 'sign-up'),
    path('sign-in/', views.login_view, name = 'sign-in'),
    path('sign-out/', views.logout_view, name = 'sign-out'),
    # path('profile/update/', views.profile_update, name = 'profile-update'),


]

templates/partials/blank.html
{% load static %}

<!DOCTYPE html>
<html lang="fa-IR">

<head>
    <meta charset="utf-8">
    <title>dejavu planners</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/faviconimage.png' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js">
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet"></link>
    <style>
        body 
        {font-family: 'Times New Roman', Times, serif;};
        

    </style>

</head>

<body style="a">
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="{% url 'core:contact' %}">سوال داری؟</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="{% url 'core:contact' %}">کمک</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="{% url 'core:contact' %}">پشتیبانی</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    
                    <a class="text-dark px-2" href="https://instagram.com/dejavuplanner.ir?igshid=OGQ5ZDc2ODk2ZA==">
                        <i class="fab fa-instagram"></i>
                        
                    </a>
                    
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><img src="{% static 'img/frame1.png' %}" alt="">planner</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="{% url 'core:search' %}" method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="جستجو" name="q">
                        &nbsp;
                        &nbsp;
                        <div class="input-group-append">
                            &nbsp;
                            <span class="input-group-text bg-transparent text-primary">
                                &nbsp;
                                <button class="fa fa-search" style="background-color: white; border: none; " type="submit" ></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                
                <a href="{% url 'core:cart' %}" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge cart-items-count">{{ request.session.cart_data_obj|length }}</span>
                </a>
                <a href="{% url 'core:dashboard' %}" class="btn border">
                    <i class="fas fa-user text-primary"></i>
                    <span class="badge "></span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid mb-5">
        <div class="row border-top px-xl-5">


            <div style="border-color: black;">
                <p>              </p>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        
                        <h1 class="m-0 display-5 font-weight-semi-bold"><img src="{% static 'img/frame1.png' %}" alt="">planner</h1>

                        <!-- <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">DV</span>planner</h1> -->
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            
                            <a href="{% url 'core:index' %}" class="nav-item nav-link active">Home</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">دسته بندی ها</a>
                                <div class="dropdown-menu rounded-0 m-0">
                                    {% for c in categories %}
                                    <li><a href="{% url 'core:category-product-list' c.cid %}" class="dropdown-item">{{c.title}}</a></li>
                                    {% endfor %}
                                    <hr>
                                    <li><a href="{% url 'core:category-list' %}" class="dropdown-item">تمام دسته بندی ها</a></li>

                                </div>
                            </div>
                            <a href="{% url 'core:product-list' %}" class="nav-item nav-link">تمام محصولات</a>
                            <!-- {% for c in categories %}
                            <a href="{% url 'core:category-product-list' c.cid %}" class="nav-item nav-link">{{c.title}}</a>
                            {% endfor %} -->
                            <!-- <a href="" class="nav-item nav-link">پلنر</a>
                            <a href="" class="nav-item nav-link">دفتر و ژورنال</a>
                            <a href="" class="nav-item nav-link">اکسسوری</a> -->

                            
                            
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">سبد خرید</a>
                                <div class="dropdown-menu rounded-0 m-0">
                                    <a href="{% url 'core:cart' %}" class="dropdown-item">سبد خرید</a>
                                    <a href="{% url 'core:checkout' %}" class="dropdown-item">تکمیل خرید</a>
                                </div>
                            </div>
                            <a href="{% url 'core:contact' %}" class="nav-item nav-link">تماس با ما</a>
                            

                            </div>
                            <div class="navbar-nav ml-auto py-0">
                                {% if request.user.is_authenticated %}
                                <a href="{% url 'userauths:sign-out' %}" class="nav-item nav-link">خروج</a>
                                {% else %}
                                <a href="{% url 'userauths:sign-in' %}" class="nav-item nav-link">ورود</a>
                                
                                <a href="{% url 'userauths:sign-up' %}" class="nav-item nav-link">ثبت نام</a>
                                {% endif %}
                            </div>
                        </div>
                    </nav>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{message}}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close")
                    }, 3000) 
                </script>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

    {% block content %}

    {% endblock content %}


    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">DV</span>planner</h1>
                </a>
                <p>bla bla.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>ارسال به کل ایران</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>dejavuplanner.dv@gmail.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>شماره تماس</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="{% url 'core:index' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="{% url 'core:product-list' %}"><i class="fa fa-angle-right mr-2"></i>فروشگاه ما</a>
                            
                            <a class="text-dark mb-2" href="{% url 'core:cart' %}"><i class="fa fa-angle-right mr-2"></i>سبد خرید</a>
                            
                            <a class="text-dark" href="{% url 'core:contact' %}"><i class="fa fa-angle-right mr-2"></i>تماس با ما</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">فضای مجازی</h5>
                        <div class="d-flex flex-column justify-content-start">
                            
                            
                            <a class="text-dark px-2" href="https://instagram.com/dejavuplanner.ir?igshid=OGQ5ZDc2ODk2ZA==">
                                <i class="fab fa-instagram"></i>
                            </a>
                            
                            
                        </div>
                    </div>
                    <!-- <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div> -->
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">dejavuplanner.ir</a>. All Rights Reserved. 
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com"></a>
                </p>
            </div>
            <!-- <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
            </div> -->
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/function.js' %}"></script>



</body>

</html>