core/urls.py
from django.urls import path
from core.views import *

app_name = "core"
urlpatterns = [
    path("", index, name = "index"),
    path("products/", product_list_view, name = "product-list"),
    path("product/<pid>/", product_detail_view, name = "product-detail"),
    path("category/", category_list_view, name = "category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    path("custom/", custom_product_list, name="custom"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax_add_review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("checkout/", checkout_view, name="checkout"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("payment-compeleted/", payment_compeleted_view, name="payment-compeleted"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-adress/", make_adress_default, name="make-default-adress"),
    path("contact/", contact_view, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


    path("checkout-information/", checkout_information_view, name="checkout-information"),




    




]

plannershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]   


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/forms.py
from stripe import Review
from django import forms
from core.models import *


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "write review"}))


    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import  JsonResponse
from taggit.models import Tag
from core.models import *
from userauths.models import *
from django.contrib import messages
from django.db.models import Avg
from core.forms import *
from userauths.forms import *
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required









def index(request):
    # product = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status= "published",featured = True)
    category = Category.objects.all().exclude(id=6)
    categorynav = Category.objects.all()
    

    if request.method == "POST":
        
        about = request.POST["aboutjoboffer"]
        email = request.POST["emailjoboffer"]
        


        new_job = JobOffer.objects.create(
            
            about=about,
            email=email,
            
        )
        new_job.save()
        messages.success(request, "باتشکر")
        return redirect("core:index")
    else:
        print("error")


    context = {
        "products": products,
        "categories": category,
        "categorynav": categorynav,

    }
    return render(request, 'core/index.html', context)




def blank(request):
    
    categorynav = Category.objects.all()
    context = {
        
        "categorynav": categorynav,

    }
    return render(request, 'core/blank.html', context)




def product_list_view(request):
    products = Product.objects.filter(product_status= "published")

    context = {
        "products": products
    }
    return render(request, 'core/product-list.html', context)




def category_list_view(request):
    category = Category.objects.all()
    context = {
        "categories": category
    }
    return render(request, 'core/category-list.html', context)




def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status= "published", category=category)
    context = {
        "category": category,
        "products": products,
    }
    return render(request, 'core/category-product-list.html', context)




def custom_product_list(request):

    products = Product.objects.filter(product_status= "published")
    context = {
        "products": products,
    }
    return render(request, 'core/custom.html', context)




def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)

    # product = get_object_or_404(Product, pid=pid)
    p_image = product.p_images.all()
    
    products = Product.objects.filter(category=product.category).exclude(pid=pid)
    addproduct = Product.objects.filter(product_status= "disabled")


    
    # creating reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    # getting average review
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating = Avg('rating'))
    # product review form 
    review_form = ProductReviewForm()

    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user = request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    context = {
        "product": product,
        "addproduct": addproduct,
        "make_review": make_review,
        "p_image": p_image,
        "products": products,
        "reviews": reviews,
        "average_rating": average_rating,
        "review_form": review_form,
        

    }

    return render(request, "core/product-detail.html", context)




def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status = "published").order_by("-id")


    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])


    context = {
        "products": products,
        "tag": tag,
    }
    return render(request, "core/tag.html", context)




def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )



    context = {
        "user": user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],


    }
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))


    return JsonResponse(
        {
        'bool': True,
        'context': context,
        'average_reviews': average_reviews,
        }
    )




def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }

    return render(request, "core/search.html", context)




def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("Vendor[]")
    typecategory = request.GET.getlist("typecategory[]")
    sizecategory = request.GET.getlist("sizecategory[]")
    tagcategory = request.GET.getlist("tagcategory[]")
    colorcategory = request.GET.getlist("colorcategory[]")
    languagecategory = request.GET.getlist("languagecategory[]")
    # و بقیه فبتر ها مانند وندور
    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(Vendor__id__in=vendors).distinct()

    if len(typecategory) > 0:
        products = products.filter(typecategory__id__in=typecategory).distinct()
    if len(sizecategory) > 0:
        products = products.filter(sizecategory__id__in=sizecategory).distinct()
    if len(tagcategory) > 0:
        products = products.filter(tagcategory__id__in=tagcategory).distinct()
    if len(colorcategory) > 0:
        products = products.filter(colorcategory__id__in=colorcategory).distinct()
    if len(languagecategory) > 0:
        products = products.filter(languagecategory__id__in=languagecategory).distinct()


    data = render_to_string("core/async/product-list.html",{"products": products})
    return JsonResponse({"data":data})



def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],

    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data

        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data

    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})



def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * int(item['price'])
        return render(request, "core/cart.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    else:
        messages.warning(request, "سبد خرید شما خالی است")
        return redirect("core:index")



def delete_item_from_cart(request):
    product_id = str(request.GET["id"]) 
    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            del request.session["cart_data_obj"][product_id]
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * int(item['price'])

    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})



def update_cart(request):
    product_id = str(request.GET["id"]) 
    product_qty = request.GET["qty"]
    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * int(item['price'])

    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})



@login_required
def checkout_view(request):
    adress = Adress.objects.filter(user=request.user)

    cart_total_amount = 0
    total_amount = 0
    # checking if cart_data_obj session exist

templates/core/cart.html
{% extends 'partials/blank.html' %}

{% load static %}

{% block content %}

<div class="main" id="cart-list">
    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 150px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">سبد خرید</h1>
            <div class="d-inline-flex">
                
                <!-- <p class="m-0">Shopping Cart</p> -->
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>محصولات</th>
                            <th>قیمت</th>
                            <th>تعداد</th>
                            <th>جمع قیمت</th>
                            <th>refresh</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for product_id, item in cart_data.items %}
                        <tr>
                            <td class="align-middle"><img src="{{ item.image }}" alt="" style="width: 50px;">&nbsp;<a href="{% url 'core:product-detail' item.pid%}">{{item.title}}</a></td>
                            
                            <td class="align-middle">{{item.price}} تومن</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center product-qty-{{product_id}}" value="{{item.qty}}" >
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">{% widthratio item.price 1 item.qty %} تومن</td>
                            <td class="align-middle " id="" data-title="refresh"><button class="btn btn-sm btn-primary update-product"  data-product="{{product_id}}"><i class="fa fa-refresh"></i></button></td>

                            <td class="align-middle " id="" data-title="remove"><button class="btn btn-sm btn-primary delete-product"  data-product="{{product_id}}"><i class="fa fa-trash"></i></button></td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <!-- <form class="mb-5" action="">
                    <div class="input-group">
                        <input type="text" class="form-control p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary"></button>
                        </div>
                    </div>
                </form> -->
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">سبد خرید</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">جمع قیمت محصولات</h6>
                            <h6 class="font-weight-medium">{{cart_total_amount}}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">ارسال</h6>
                            <h6 class="font-weight-medium">رایگان</h6>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">جمع کل پرداختی</h5>
                            <h5 class="font-weight-bold">{{cart_total_amount}}</h5>
                        </div>
                        {% if totalcartitems %}
                        <a href="{% url 'core:checkout-information' %}" class="btn btn-block btn-primary my-3 py-3">ادامه خرید</a>
                        {% endif %}                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->
</div>

 
    
    

    {% endblock content %}

templates/core/category-list.html
{% extends 'partials/blank.html' %}
{% load static %}



    {% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 150px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">لیست دسته بندی</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">feel free to explore</a></p>
                
            </div>
        </div>
    </div>
    <!-- Page Header End -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            {% for c in categories %}
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">{{c.title}}</p>
                    <a href="{% url 'core:category-product-list' c.cid %}" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="{{ c.image.url }}" alt="">
                    </a>
                    

                    <h5 class="font-weight-semi-bold m-0">محصول {{c.category.count}}</h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endblock content %}

templates/core/category-product-list.html
{% extends 'partials/blank.html' %}

{% load static %}

{% block content %}
        <div class="container-fluid bg-secondary mb-5">
            <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 150px">
                <h1 class="font-weight-semi-bold text-uppercase mb-3">({{category.title}})لیست محصولات</h1>
                <div class="d-inline-flex">
                    <p class="m-0"><a href="{% url 'core:index' %}">Home</a></p>
                    <p class="m-0 px-2">-</p>
                    <p class="m-0">{{category.title}}</p>
                </div>
                &nbsp;
                <div class="d-inline-flex">
                    <p class="p-left">{{products.count}} محصول </p>
                </div>
            </div>
        </div>
        <div class="container-fluid pt-5">

            <div class="row px-xl-5 pb-3">
                <!-- --------------------------------------------------------------------- -->
                {% for p in products  %}                

                <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <a href="{% url 'core:product-detail' p.pid %}">
                                <img class="img-fluid w-100" src="{{ p.image.url }}" alt="">
                            </a>
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{ p.title }}</h6>
                            <h6 class="ligh">category: {{ p.category }}</h6>
                            <br> 
                            <div class="d-flex justify-content-center">
                                <h6 class="current-product-price-{{ p.id }}">{{ p.price }} </h6><sup>- {{ p.get_precentage|floatformat:0 }}%</sup> <h6 class="text-muted ml-2"><del>{{ p.old_price }}</del></h6><span> تومن </span>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>جزییات</a>
                            <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{p.id}}">
                            <input type="hidden" class="product-pid-{{p.id}}" value="{{p.pid}}">
                            <input type="hidden" class="product-image-{{p.id}}" value="{{p.image.url}}">
                            <input type="hidden" class="product-id-{{p.id}}" value="{{p.id}}">
                            <input type="hidden" class="product-title-{{p.id}}" value="{{p.title}}">
                            <button  class="btn btn-sm text-dark p-0 add-to-cart-btn" data-index="{{ p.id }}" id="add-to-cart-btn"><i class="fas fa-shopping-cart text-primary mr-1"></i>افزودن به سبد خرید</button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock content %}

templates/core/checkout.html
{% extends 'partials/blank.html' %}

{% load static %}

{% block content %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 150px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">تکمیل خرید</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">تکمیل خرید</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Checkout Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8" >
                <div class="mb-4">
                    <h4 class="font-weight-semi-bold mb-4">آدرس و مشخصات ارسال</h4>
                    <div class="row">
                        {% for a in adress %}
                        <div class="col-md-6 form-group">
                            <label>نام</label>
                            <h6>{{a.firstname}}</h6>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>نام خانوادگی</label>
                            <h6>{{a.lastname}}</h6>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>تلفن همراه</label>
                            <h6>{{a.mobile}}</h6>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>ادرس</label>
                            <h6>{{a.adress}}</h6>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>کدپستی</label>
                            <h6>{{a.postcode}}</h6>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>استان ،شهر</label>
                            <h6>{{a.stateadress}}, {{a.city}}</h6>
                        </div>
                        
                        
                        
                        {% endfor %}
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">جمع سبد کالا</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-footer border-secondary bg-transparent">
                            <!-- <a class="btn btn-primary align-items-center" href="{% url 'core:cart' %}">بازگشت به سبد خرید</a> -->
                        </div>
                        <h5 class="font-weight-medium mb-3">کالا ها</h5>
                        {% for product_id, item in cart_data.items %}
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'core:product-detail' item.pid %}">{{item.title}}<img class="img-fluid"  src="{{item.image}}" alt=""></a>
                            <h6>{{item.price}}</h6>
                            <h6>*{{item.qty}}</h6>
                            <h6>={% widthratio item.price 1 item.qty %}</h6>
                            
                            
                        </div>
                        {% endfor %}
                        
                        <hr class="mt-0">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">جمع سبدخرید</h6>
                            <h6 class="font-weight-medium">{{cart_total_amount}}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">ارسال</h6>
                            <h6 class="font-weight-medium">رایگان</h6>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">جمع خرید</h5>
                            <h5 class="font-weight-bold">{{cart_total_amount}}</h5>
                        </div>
                    </div>
                </div>
                <!-- <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Payment</h4>
                    </div> -->
                    <!-- <div class="card-body">
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="paypal">
                                <label class="custom-control-label" for="paypal">Paypal</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                                <label class="custom-control-label" for="directcheck">Direct Check</label>
                            </div>
                        </div>
                        <div class="">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                            </div>
                        </div>
                    </div> -->
                    <div class="card-footer border-secondary bg-transparent">
                        <button class="btn btn-lg btn-block btn-primary font-weight-bold my-3 py-3">ثبت سفارش</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

{% endblock content %}

templates/core/search.html
{% extends 'partials/blank.html' %}

{% load static %}

{% block content %}
        <div class="container-fluid bg-secondary mb-5">
            <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 150px">
                {% if query %}
                    <h1 class="font-weight-semi-bold text-uppercase mb-3">{{query}}</h1>
                {% else %}
                    <h1 class="font-weight-semi-bold text-uppercase mb-3">محصولات</h1>
                {% endif %}    
                <div class="d-inline-flex">
                    
                    <!-- <p class="m-0">{{query}}</p> -->
                </div>
                <div class="d-inline-flex">
                    <p class="p-left">{{products.count}} محصول </p>
                    
                </div>
            </div>
        </div>
        <div class="container-fluid pt-5">

            <div class="row px-xl-5 pb-3">
                <!-- --------------------------------------------------------------------- -->
                {% for p in products  %}                

                <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <a href="{% url 'core:product-detail' p.pid %}">
                                <img class="img-fluid w-100" src="{{ p.image.url }}" alt="">
                            </a>
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{ p.title }}</h6>
                            <p class="text-truncate mb-3">دسته بندی: {{ p.category }}</p>

                            <div class="d-flex justify-content-center">
                                <h6>{{ p.price }} <sup> {{ p.get_precentage|floatformat:0 }}%</sup> </h6><h6 class="text-muted ml-2"><del>{{ p.old_price }}</del></h6>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>جزییات</a>
                            <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>افزودن به سبد خرید</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock content %}