core/urls.py
from django.urls import path
from core.views import *

app_name = "core"
urlpatterns = [
    path("", index, name = "index"),
    path("products/", product_list_view, name = "product-list"),
    path("product/<pid>/", product_detail_view, name = "product-detail"),
    path("category/", category_list_view, name = "category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    path("custom/", custom_product_list, name="custom"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax_add_review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("checkout/", checkout_view, name="checkout"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("payment-compeleted/", payment_compeleted_view, name="payment-compeleted"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-adress/", make_adress_default, name="make-default-adress"),
    path("contact/", contact_view, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


    path("checkout-information/", checkout_information_view, name="checkout-information"),




    




]

plannershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]   


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.register_view, name = 'sign-up'),
    path('sign-in/', views.login_view, name = 'sign-in'),
    path('sign-out/', views.logout_view, name = 'sign-out'),
    # path('profile/update/', views.profile_update, name = 'profile-update'),


]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']


    def __str__ (self):
        return self.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default="")
    image = models.ImageField(upload_to="image", null=True, blank=True)
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    verified = models.BooleanField(default=False)





    def __str__ (self):
        return self.full_name
    
class ContactUs(models.Model):
    full_name = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.TextField()
    subject = models.CharField(max_length=200)




    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"


    def __str__ (self):
        return self.full_name
    

class JobOffer(models.Model):
    about = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)

    def __str__ (self):
        return self.about



 

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import *


class UserRegisterForm(UserCreationForm):

    username = forms.CharField(widget= forms.TextInput(attrs={"placeholder": "username"}))
    email = forms.EmailField(widget= forms.EmailInput(attrs={"placeholder": "email"}))
    password1 = forms.CharField(widget= forms.PasswordInput(attrs={"placeholder": "password"}))
    password2 = forms.CharField(widget= forms.PasswordInput(attrs={"placeholder": "comfrim password"}))

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"full name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"phone"}))

    class Meta:
        model= Profile
        fields = ["full_name", "image", "bio", "phone"]

userauths/views.py
from django.shortcuts import render,redirect
from userauths.forms import  *
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User
from core.models import *


# User = settings.AUTH_USER_MODEL


# register view

def register_view(request):



    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request,  "اکانت شما با موفقیت ساخته شد")
            new_user = authenticate(username = form.cleaned_data["email"], 
                                    password = form.cleaned_data["password1"]
            )
            login(request, new_user)
            return redirect("core:index")



    else:
        form = UserRegisterForm()


    context = {
        'form': form,
    }
    return render(request, "userauths/sign-up.html", context)



# login view
def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f".قبلا ورود کرده اید")
        return redirect('core:index')
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email = email)
            user = authenticate(request, email = email, password = password)

            if user is not None:
                login(request, user)
                messages.success(request,"you are logged in")
                return redirect("core:index")
            
            else:
                messages.warning(request, ".اکانتی وجود نداره لطفا ثبت نام کنید")
                # return redirect("userauths/sign-up.html")
        except:
            messages.warning(request, f"user with {email} does not exist")
            return redirect("core:index")


             

    context = {

    }

    return render(request, "userauths/sign-in.html", context)



# loggin out view
def logout_view(request):
    logout(request)
    messages.success(request, ".با موفقیت از اکانت خود خارج شدید")

    return redirect("core:index")
    # return render(request, "userauths/sign-in.html")



# update profile
def profile_update(request):
    form = ProfileForm()
    user_profile = Profile.objects.get(user=request.user)
    orders = CartOrder.objects.filter(user=request.user).order_by("-id")
    adress = Adress.objects.filter(user=request.user)
    
    

    if request.method == "POST":
        adress = request.POST.get("adress")
        mobile = request.POST.get("mobile")

        new_adress = Adress.objects.create(
            user=request.user,
            adress=adress,
            mobile=mobile,
        )
        messages.success(request, "آدرس با موفقیت اضافه شد")
        return redirect("core:dashboard")
    else:
        print("error")
    user_profile = Profile.objects.get(user=request.user)

    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, "profile updated successfully.")
            return redirect("core:dashboard")
        
        else:
            form = ProfileForm(instance=profile)




    context = {
        
        "form": form,
        "profile": profile,
        "orders": orders,
        "adress": adress,
        "user_profile": user_profile,


    }
    return render(request, "userauths/profile-edit.html", context)

templates/userauths/profile-edit.html
{% extends 'partials/blank.html' %}

{% load static %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <h3>edit profile</h3>
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <!-- {% if profile.image %} -->
                <!-- <img class="rounded-circle mt-5" width="150px" height="150px"   style="object-fit: cover; border-radius: 50%;" src="{{profile.image.url}}"> -->

                <!-- {% else %} -->
                <img class="rounded-circle mt-5" width="150px" height="150px"   style="object-fit: cover; border-radius: 50%;" src="{% static 'img/download.jpg' %}">
                <!-- {% endif %} -->
                &nbsp;
                <!-- <span class="font-weight-bold"><input type="text" value="اسم:{{user_profile.full_name}}" class="form-control"></span>
                <span class="text-black-50"><input type="text" value="ایمیل:{{user_profile.email}}" class="form-control"></span>
                <span class="font-weight-bold"><input type="text" value="بایو:{{user_profile.bio}}" class="form-control"></span>
                <span class="font-weight-bold"><input type="text" value="تلفن همراه:{{user_profile.phone}}" class="form-control"></span>
                 -->
                 <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">{{form.full_name}}</div>
                    <div class="mb-3">{{form.bio}}</div>
                    <div class="mb-3">{{form.phone}}</div>
                    <!-- <div class="mb-3">{{form.image}}</div> -->
                    <button type="submit" class="btn btn-primary">ذخیره</button>


                 </form>
                
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <!-- <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Name</label><input type="text" class="form-control" placeholder="first name" value=""></div>
                    <div class="col-md-6"><label class="labels">Surname</label><input type="text" class="form-control" value="" placeholder="surname"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Mobile Number</label><input type="text" class="form-control" placeholder="enter phone number" value=""></div>
                    <div class="col-md-12"><label class="labels">Address Line 1</label><input type="text" class="form-control" placeholder="enter address line 1" value=""></div>
                    <div class="col-md-12"><label class="labels">Address Line 2</label><input type="text" class="form-control" placeholder="enter address line 2" value=""></div>
                    <div class="col-md-12"><label class="labels">Postcode</label><input type="text" class="form-control" placeholder="enter address line 2" value=""></div>
                    <div class="col-md-12"><label class="labels">State</label><input type="text" class="form-control" placeholder="enter address line 2" value=""></div>
                    <div class="col-md-12"><label class="labels">Area</label><input type="text" class="form-control" placeholder="enter address line 2" value=""></div>
                    <div class="col-md-12"><label class="labels">Email ID</label><input type="text" class="form-control" placeholder="enter email id" value=""></div>
                    <div class="col-md-12"><label class="labels">Education</label><input type="text" class="form-control" placeholder="education" value=""></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><label class="labels">Country</label><input type="text" class="form-control" placeholder="country" value=""></div>
                    <div class="col-md-6"><label class="labels">State/Region</label><input type="text" class="form-control" value="" placeholder="state"></div>
                </div>
                <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save Profile</button></div> -->


                <div>
                    <form class="mb-4" action="" method="POST">
                        {% csrf_token %}
                        <div class="card-header">
                            <h5>add adress</h5>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <input type="text" placeholder="adress" required="" class="form-control" name="adress">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="text" placeholder="mobile", required="" class="form-control" name="mobile">

                            </div>
                        
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary font-weight-bold" name="submit" value="submit">save adress</button>
                        </div>
                    </form>
                </div>

                {% for a in adress %}
                <div>
                    
                    <h4 class="font-weight-bold mb-3">adress {{forloop.counter}}</h4>
                    
                    <p>{{a.adress}}</p>
                    <p>{{a.mobile}}</p>
                    
                    {% if a.status %}
                        <i data-adress-id="{{a.id}}" class="fas fa-check-circle check check{{a.id}}" ></i>
                        <button data-adress-id="{{a.id}}" style="display: none;" class="btn btn-primary font-weight-bold make-default-adress button{{a.id}} action_btn">make default </button>
                    {% else %}
                        <i data-adress-id="{{a.id}}" class="fas fa-check-circle check check{{a.id}} " style="display: none;"></i>
                        <button data-adress-id="{{a.id}}" class="btn btn-primary font-weight-bold make-default-adress button{{a.id}} action_btn">make default </button>
                        
                    {%endif%}
                    <br>
                </div>
                {% endfor %}
                
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center experience"><span>Edit Experience</span><span class="border px-3 p-1 add-experience"><i class="fa fa-plus"></i>&nbsp;Experience</span></div><br>
                <div class="col-md-12"><label class="labels">Experience in Designing</label><input type="text" class="form-control" placeholder="experience" value=""></div> <br>
                <div class="col-md-12"><label class="labels">Additional Details</label><input type="text" class="form-control" placeholder="additional details" value=""></div>
            </div>
            <div class="">
                <table class="table">
                    <thead>
                        <tr>
                            <th>order</th>
                            <th>date</th>
                            <th>status</th>
                            <th>paid status</th>
                            <th>total</th>
                            <th>action</th>
                        </tr>

                    </thead>
                    <tbpdy>
                        {% for o in orders %}
                        <tr>
                            <td>invoice_no-{{o.id}}</td>
                            <td>{{o.order_date}}</td>
                            <td>{{o.product_status|title}}</td>
                            {% if o.paid_status == True %}
                            <td class="fas fa-check"></td>
                            {% else %}
                            <td class="fas fa-xmark"></td>
                            {% endif %}
                            
                            <td>{{o.price}}</td>
                            <td><a href="{% url 'core:order-detail' o.id %}">view</a></td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock content %}

templates/userauths/sign-in.html
<!-- <form action="", method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">register</button>
</form> -->


{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title> sign-up / sign-in form</title>
  <link rel="stylesheet" href="{% static 'sign-up/style.css' %}">
  <link href="{% static 'img/faviconimage.png' %}" rel="icon">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <!-- <img src="{% static 'img/desktop.png' %}" alt=""> -->
  <div class="container">
    <div class="sign-up-container">
      <form action = "", method="POST">
        {% csrf_token %}
        <h1>ورود به اکانت</h1>
        <!-- {{form.email}}
        {{form.password1}} -->


        <!-- {% if form.errors %}
        <div class = "alert  aler-danger">
            <strong>{{form.errors}}</strong>
        </div>
        {% endif %} -->
        <!-- <div class="social-links">
          <div>
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          </div>
          <div>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </div>
          <div>
            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
          </div>
        </div> -->
        <span></span>
        <!-- <input type="text" required name="" placeholder="Name"> -->
        <input type="email" required name="email" placeholder="Email">
        <input type="password" required name="password" placeholder="Password">
        <button type="submit" class="form_btn">ورود به اکانت</button>
        <a href="{% url 'userauths:sign-up' %}"><h6 >هنوز ثبت نام نکردی؟</h6></a>
      </form>
    </div>
    <div class="sign-in-container">
      <img src="{% static 'img/dd3.png' %}" alt="">
    </div>
    <div class="overlay-container">
      <div class="overlay-left">
        <img src="{% static 'img/dd3.png' %}" alt="">
      </div>
      <div class="overlay-right">
        <h1>Hello, Friend</h1>
        
        <button id="signUp" class="overlay_btn">ورود</button>
      </div>
    </div>
  </div>
</div>
 <!-- partial -->
  <script  src="{% static 'sign-up/script.js' %}"></script>

</body>
</html>

templates/userauths/sign-up.html
<!-- <form action="", method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">register</button>
</form> -->


{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title> sign-up / sign-in form</title>
  <link rel="stylesheet" href="{% static 'sign-up/style.css' %}">
  <link href="{% static 'img/faviconimage.png' %}" rel="icon">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <!-- <img src="{% static 'img/desktop.png' %}" alt=""> -->
  <div class="container">
    <div class="sign-up-container">
      <form action = "", method="POST">
        {% csrf_token %}
        <h1>ثبت نام</h1>
        &nbsp;
        {{form.username}}
        {{form.email}}
        {{form.password1}}
        {{form.password2}}


        {% if form.errors %}
        <div class = "alert  aler-danger">
            <strong>{{form.errors}}</strong>
        </div>
        {% endif %}
        
        <!-- <div class="social-links">
          <div>
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          </div>
          <div>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </div>
          <div>
            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
          </div>
        </div> -->
        <!-- <span>or use your email for registration</span> -->
        <!-- <input type="text" placeholder="Name">
        <input type="email" placeholder="Email">
        <input type="password" placeholder="Password"> -->
        <button type="submit" class="form_btn">ثبت نام</button>
        <a href="{% url 'userauths:sign-in' %}"><h6 >قبلا ثبت نام کردی؟</h6></a>
      </form>
      
    </div>
    
    <div class="sign-in-container">
      <img src="{% static 'img/dd3.png' %}" alt="">
    </div>
    <div class="overlay-container">
      <div class="overlay-left">
        
        <img src="{% static 'img/dd3.png' %}" alt="">
        
        <!-- <button formaction="{% url 'userauths:sign-in' %}" id="" class="">ورود کن</button> -->
        <!-- <a class="a1" href="{% url 'userauths:sign-in' %}">ورود</a> -->
      </div>
      <div class="overlay-right">
        <h1>Hello, Friend</h1>
        
        <button id="signUp" class="overlay_btn">ثبت نام</button>
      </div>
    </div>
  </div>
</div>
 <!-- partial -->
  <script  src="{% static 'sign-up/script.js' %}"></script>

</body>
</html>